name: CI
on:
    push: {}
    pull_request: {}
    schedule:
        - cron: "*/15 * * * *"

jobs:
  publish_archive_job:
    runs-on: ubuntu-latest
    name: A job to publish zulip-archive in GitHub pages
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run archive
      id: archive
      uses: zulip/zulip-archive@master
      with:
        zulip_organization_url: ${{ secrets.zulip_organization_url }}
        zulip_bot_email: ${{ secrets.zulip_bot_email }}
        zulip_bot_key: ${{ secrets.zulip_bot_key }}
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        delete_history: true
        archive_branch: gh-pages
    - name: Generate old link format
      run: |
          mkdir 268952edition2021
          echo '<meta http-equiv="Refresh" content="0; url=\'/stream/268952-edition-2021/topic/.22Rust.202021.20dry.20run.22.20crater.20run.html\'" />' > 268952edition2021/01650Rust2021dryruncraterrun.html
          git config --global user.name 'Zulip Bot'
          git config --global user.email 'zulip-archive-bot@users.noreply.github.com'
          git commit -am "Create redirect pages"
          git push
