name: CI
on:
    push:
        branches:
            - master
    schedule:
        - cron: "*/15 * * * *"

jobs:
  publish_archive_job:
    runs-on: ubuntu-latest
    name: A job to publish zulip-archive in GitHub pages
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Run archive
      id: archive
      uses: zulip/zulip-archive@master
      with:
        zulip_organization_url: ${{ secrets.zulip_organization_url }}
        zulip_bot_email: ${{ secrets.zulip_bot_email }}
        zulip_bot_key: ${{ secrets.zulip_bot_key }}
        github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        delete_history: true
        archive_branch: gh-pages
    - name: Generate old link format
      run: |
          wget https://raw.githubusercontent.com/rust-lang/zulip_archive/master/generate-old.sh
          chmod u+x ./generate-old.sh
          ./generate-old.sh
          git config --global user.name 'Zulip Bot'
          git config --global user.email 'zulip-archive-bot@users.noreply.github.com'
          git commit -am "Create redirect pages"
          git push
